name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: 161.35.76.232
          key: droplet # Private or public key of the server
          username: root # User of the server you want to ssh into
     
          script: |
            mkdir test 
            cd test 
            git clone git@github.com:medkhalilbk/ci-pipeline-droplet.git 
            echo 'Deployment successful to digital ocean' 
